### ISSUE TITLE
typo (propably?)

### ISSUE THREAD

**Issue by Martin-Eckleben** [SilverTiger/lwjgl3-tutorial#1]
In your tutorial you state:
        int vao = glGenVertexArrays();
        glBindVertexArrays(vao);

But I cant find glBindVertexArrays in any GL*\* class.
Only glBindVertexArray
Did you mean that or do I fail to understand some basics?

**Comment by SilverTiger** [comment]
Yeah, you are right, it should be `glBindVertexArray(vao)` from the `GL30` class as it can be seen [here](http://javadoc.lwjgl.org/org/lwjgl/opengl/GL30.html#glBindVertexArray%28int%29).
Thanks for pointing it out!

Fixed that typo just now.
