### ISSUE TITLE
Add alpha support for textures

### ISSUE THREAD

**Issue by matt-pan** [SilverTiger/lwjgl3-tutorial#10]
Hi,

One small suggestion from my side for this very helping tutorial would be to change the color vec3 to a vec4 so that textures can have an alpha value applied too. The Color class has an alpha member (and getter/setter) already but it is not used by the Renderer at all. I tried to change this myself but apparently I wasn't able to do it right.

**Comment by SilverTiger** [comment]
Thanks for the Suggestion. I will look into this.

**Comment by matt-pan** [comment]
Thanks a lot
