### ISSUE TITLE
"Rendering" tutorial mysteriously isn't working

### ISSUE THREAD

**Issue by AmiableNebula** [SilverTiger/lwjgl3-tutorial#13]
I seem to have run into a problem during the "Rendering" part of the tutorial. As far as I can tell, I've done everything as you did (except I used JOML, but I can't see a difference between your Matrix4f() implementation and its) but I can't seem to actually render anything to the screen. I've been scratching my head over this for a few days and I can't for the life of me figure out what I'm doing differently that would break anything. My code so far is on my [repository](https://github.com/AmiableNebula/lwjgl3-learning) and I was wondering if you'd be willing to take a look at it to try to see if you can figure it out, perhaps?

Thanks,
Sarah

**Comment by SilverTiger** [comment]
On the first sight I don't see any obvious errors... but I'll take a closer look tomorrow :)

**Comment by AmiableNebula** [comment]
Update: I figured out I was using an incorrect offset when setting the vertex color atrribute.
