### ISSUE TITLE
Bug in Renderer.drawTextureRegion() with vertices size

### ISSUE THREAD

**Issue by TheChocolateOre** [SilverTiger/lwjgl3-tutorial#16]
In line 352 you check if the space in vertices buffer is not enought and if so you flush it.
```java
if (vertices.remaining() < 7 * 6) {
    /* We need more space in the buffer, so flush it */
    flush();
}
```

 But, the threshold is `7 * 6`. Shouldn't it be `8 * 6` or `vertices.remaining() <= 7 * 6`?

**Comment by SilverTiger** [comment]
You're right... I overlooked it when adding the alpha color support. Thanks!
