### ISSUE TITLE
Setup wiki page snippet doesn't compile (wrong import)

### ISSUE THREAD

**Issue by jacobmaxfrank** [SilverTiger/lwjgl3-tutorial#5]
Unless I'm doing something wrong, the class `org.lwjgl.Sys` does not exist in the specified version (3.0.0b).  This code works for me:

```
import org.lwjgl.Version;

public class Schematic {
    public static void main(String[] args) {
        System.out.println("LWJGL Version " + Version.getVersion() + " is working.");
    }
}
```

**Comment by SilverTiger** [comment]
You're right, I overlooked that import when I did the update from 3.0.0a to 3.0.0b, shoud be fixed now!
Thanks for pointing that out!
